version: '3'

services:
  nats-server:
    image: nats:latest

  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: us-west2-docker.pkg.dev/store-microservices-418519/image-registry/client-gateway
    ports:
     - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=nats://nats-server:4222

  products-ms:
    build: 
      context: ./products-ms
      dockerfile: dockerfile.prod
    image: us-west2-docker.pkg.dev/store-microservices-418519/image-registry/products-ms
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db

  orders-ms:
    build: 
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - ORDERS_MS_DATABASE_URL=${ORDERS_MS_DATABASE_URL}
    image: us-west2-docker.pkg.dev/store-microservices-418519/image-registry/orders-ms
    environment:
      - PORT=3000
      - DATABASE_URL=${ORDERS_MS_DATABASE_URL}
      - NATS_SERVERS=nats://nats-server:4222

  payments-ms:
    build: 
      context: ./payments-ms
      dockerfile: dockerfile.prod
    image: us-west2-docker.pkg.dev/store-microservices-418519/image-registry/payments-ms
    ports:
      - ${PAYMENT_MS_PORT}:${PAYMENT_MS_PORT}
    environment:
      - PORT=${PAYMENT_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SECRET_ENDPOINT=${STRIPE_SECRET_ENDPOINT}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}

  auth-ms:
    build: 
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: us-west2-docker.pkg.dev/store-microservices-418519/image-registry/auth-ms
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
